// AUTO-GENERATED by scripts/sync-loose.py — do not edit by hand.
// Source of truth: <master>/Loose/<year>/Web/. Re-run the script to update.

export interface LoosePhoto { id: string; title: string; src: string; }
export interface LooseYear { year: string; coverPhoto: string; photos: LoosePhoto[]; }

export const looseYears: LooseYear[] = [
  { year: '2026', coverPhoto: '/photography/loose/2026/01-at-ease.webp', photos: [
    { id: 'loose-2026-01', title: 'At Ease', src: '/photography/loose/2026/01-at-ease.webp' },
    { id: 'loose-2026-02', title: 'The Wish', src: '/photography/loose/2026/02-the-wish.webp' },
    { id: 'loose-2026-03', title: 'Claim', src: '/photography/loose/2026/03-claim.webp' },
    { id: 'loose-2026-04', title: 'Work', src: '/photography/loose/2026/04-work.webp' },
    { id: 'loose-2026-05', title: 'Un Mundo Distinto', src: '/photography/loose/2026/05-un-mundo-distinto.webp' },
    { id: 'loose-2026-06', title: 'Grounds', src: '/photography/loose/2026/06-grounds.webp' },
    { id: 'loose-2026-07', title: 'Common Ground', src: '/photography/loose/2026/07-common-ground.webp' },
    { id: 'loose-2026-08', title: 'Nestled', src: '/photography/loose/2026/08-nestled.webp' },
    { id: 'loose-2026-09', title: 'Lookout', src: '/photography/loose/2026/09-lookout.webp' },
    { id: 'loose-2026-10', title: 'Sovereign', src: '/photography/loose/2026/10-sovereign.webp' },
    { id: 'loose-2026-11', title: 'Wedge', src: '/photography/loose/2026/11-wedge.webp' },
    { id: 'loose-2026-12', title: 'Respite', src: '/photography/loose/2026/12-respite.webp' },
    { id: 'loose-2026-13', title: 'Generations', src: '/photography/loose/2026/13-generations.webp' },
    { id: 'loose-2026-14', title: 'Cant', src: '/photography/loose/2026/14-cant.webp' },
    { id: 'loose-2026-15', title: 'Convocation', src: '/photography/loose/2026/15-convocation.webp' },
    { id: 'loose-2026-16', title: 'Standby', src: '/photography/loose/2026/16-standby.webp' },
    { id: 'loose-2026-17', title: 'Sawtooth', src: '/photography/loose/2026/17-sawtooth.webp' },
    { id: 'loose-2026-18', title: 'Contratiempo', src: '/photography/loose/2026/18-contratiempo.webp' },
    { id: 'loose-2026-19', title: 'Nesting', src: '/photography/loose/2026/19-nesting.webp' },
    { id: 'loose-2026-20', title: 'Ripple', src: '/photography/loose/2026/20-ripple.webp' },
    { id: 'loose-2026-21', title: 'Stave', src: '/photography/loose/2026/21-stave.webp' },
    { id: 'loose-2026-22', title: 'Sweep', src: '/photography/loose/2026/22-sweep.webp' },
  ] },
  { year: '2024', coverPhoto: '/photography/loose/2024/01-threshold-keepers.webp', photos: [
    { id: 'loose-2024-01', title: 'Threshold Keepers', src: '/photography/loose/2024/01-threshold-keepers.webp' },
  ] },
  { year: '2021', coverPhoto: '/photography/loose/2021/01-dominion.webp', photos: [
    { id: 'loose-2021-01', title: 'Dominion', src: '/photography/loose/2021/01-dominion.webp' },
  ] },
  { year: '2020', coverPhoto: '/photography/loose/2020/01-the-hollow.webp', photos: [
    { id: 'loose-2020-01', title: 'The Hollow', src: '/photography/loose/2020/01-the-hollow.webp' },
  ] },
  { year: '2019', coverPhoto: '/photography/loose/2019/01-scatter.webp', photos: [
    { id: 'loose-2019-01', title: 'Scatter', src: '/photography/loose/2019/01-scatter.webp' },
  ] },
  { year: '2018', coverPhoto: '/photography/loose/2018/01-across.webp', photos: [
    { id: 'loose-2018-01', title: 'Across', src: '/photography/loose/2018/01-across.webp' },
    { id: 'loose-2018-02', title: 'Thicket', src: '/photography/loose/2018/02-thicket.webp' },
    { id: 'loose-2018-03', title: 'Three Crowns', src: '/photography/loose/2018/03-three-crowns.webp' },
    { id: 'loose-2018-04', title: 'Migration', src: '/photography/loose/2018/04-migration.webp' },
  ] },
  { year: '2017', coverPhoto: '/photography/loose/2017/01-relay.webp', photos: [
    { id: 'loose-2017-01', title: 'Relay', src: '/photography/loose/2017/01-relay.webp' },
    { id: 'loose-2017-02', title: 'Guardian', src: '/photography/loose/2017/02-guardian.webp' },
    { id: 'loose-2017-03', title: 'Supplication', src: '/photography/loose/2017/03-supplication.webp' },
    { id: 'loose-2017-04', title: 'Rampant', src: '/photography/loose/2017/04-rampant.webp' },
    { id: 'loose-2017-05', title: 'Apostle', src: '/photography/loose/2017/05-apostle.webp' },
    { id: 'loose-2017-06', title: 'Dominions', src: '/photography/loose/2017/06-dominions.webp' },
    { id: 'loose-2017-07', title: 'Pinnacle', src: '/photography/loose/2017/07-pinnacle.webp' },
    { id: 'loose-2017-08', title: 'Upheaval', src: '/photography/loose/2017/08-upheaval.webp' },
    { id: 'loose-2017-09', title: 'Surveyor', src: '/photography/loose/2017/09-surveyor.webp' },
    { id: 'loose-2017-10', title: 'Mandate', src: '/photography/loose/2017/10-mandate.webp' },
    { id: 'loose-2017-11', title: 'The Leaning', src: '/photography/loose/2017/11-the-leaning.webp' },
    { id: 'loose-2017-12', title: 'Borrowed Face', src: '/photography/loose/2017/12-borrowed-face.webp' },
    { id: 'loose-2017-13', title: 'Usurpation', src: '/photography/loose/2017/13-usurpation.webp' },
  ] },
  { year: '2016', coverPhoto: '/photography/loose/2016/01-ensign.webp', photos: [
    { id: 'loose-2016-01', title: 'Ensign', src: '/photography/loose/2016/01-ensign.webp' },
    { id: 'loose-2016-02', title: 'Inventory', src: '/photography/loose/2016/02-inventory.webp' },
    { id: 'loose-2016-03', title: 'The Gallery', src: '/photography/loose/2016/03-the-gallery.webp' },
  ] },
  { year: '2015', coverPhoto: '/photography/loose/2015/01-filaments.webp', photos: [
    { id: 'loose-2015-01', title: 'Filaments', src: '/photography/loose/2015/01-filaments.webp' },
    { id: 'loose-2015-02', title: 'The Audience', src: '/photography/loose/2015/02-the-audience.webp' },
    { id: 'loose-2015-03', title: 'Indifference', src: '/photography/loose/2015/03-indifference.webp' },
    { id: 'loose-2015-04', title: 'Goat', src: '/photography/loose/2015/04-goat.webp' },
    { id: 'loose-2015-05', title: 'The Coil', src: '/photography/loose/2015/05-the-coil.webp' },
    { id: 'loose-2015-06', title: 'Arachne', src: '/photography/loose/2015/06-arachne.webp' },
    { id: 'loose-2015-07', title: 'Velitas', src: '/photography/loose/2015/07-velitas.webp' },
  ] },
  { year: '2014', coverPhoto: '/photography/loose/2014/01-luminance.webp', photos: [
    { id: 'loose-2014-01', title: 'Luminance', src: '/photography/loose/2014/01-luminance.webp' },
    { id: 'loose-2014-02', title: 'Patterns', src: '/photography/loose/2014/02-patterns.webp' },
    { id: 'loose-2014-03', title: 'Chilling', src: '/photography/loose/2014/03-chilling.webp' },
    { id: 'loose-2014-04', title: 'Passerby', src: '/photography/loose/2014/04-passerby.webp' },
    { id: 'loose-2014-05', title: 'Web and Thorns', src: '/photography/loose/2014/05-web-and-thorns.webp' },
    { id: 'loose-2014-06', title: 'The Passage', src: '/photography/loose/2014/06-the-passage.webp' },
    { id: 'loose-2014-07', title: 'The Rock', src: '/photography/loose/2014/07-the-rock.webp' },
  ] },
  { year: '2013', coverPhoto: '/photography/loose/2013/01-tower-and-fountains.webp', photos: [
    { id: 'loose-2013-01', title: 'Tower and Fountains', src: '/photography/loose/2013/01-tower-and-fountains.webp' },
  ] },
  { year: '2012', coverPhoto: '/photography/loose/2012/01-flight.webp', photos: [
    { id: 'loose-2012-01', title: 'Flight', src: '/photography/loose/2012/01-flight.webp' },
    { id: 'loose-2012-02', title: 'Sunburst', src: '/photography/loose/2012/02-sunburst.webp' },
    { id: 'loose-2012-03', title: 'The Observer', src: '/photography/loose/2012/03-the-observer.webp' },
  ] },
];
