#!/usr/bin/env python3
"""Sync Works + Studies photos from the master archive into the repo.
Source of truth: <master>/{Works,Studies}/<Name>/Portfolio/*.jpg  (frameless).
Never the Web/ copies (square + framed = social media).

Generates:
  - webp files in public/photography/<slug>/ and public/photography/studies/<slug>/
  - a cover.webp per collection (only if missing — keeps curated covers)
  - data/generated.ts : GEN[slug] = photos pulled from the folders

The photo LISTS come from here; the descriptive metadata (statements,
quotes, order intent) stays hand-authored in data/series.ts & studies.ts,
which merge GEN over their own fallback (see data/merge.ts). Anything not
found in the folders keeps whatever the repo already had.
Run from repo root:  python3 scripts/sync-photos.py
"""
import os, re, shutil
from PIL import Image

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MASTER = os.path.abspath(os.path.join(REPO, '..', '..'))
PUB = os.path.join(REPO, 'public', 'photography')
MAXEDGE, Q = 1600, 80   # web-optimized: smaller = faster galleries
THUMB, TQ = 640, 78     # square grid thumbnails (center-crop) — grid loads these, lightbox the full webp
SRC_SUB = 'Portfolio'

def slugify(s): return re.sub(r'(^-|-$)', '', re.sub(r'[^a-z0-9]+', '-', s.lower()))
def title_from(fn):
    m = re.match(r'^\d{8}_(.+)_' + SRC_SUB.lower() + r'\.(jpe?g|png|webp)$', fn, re.I)
    return m.group(1).replace('_', ' ') if m else None
def date_from(fn):
    m = re.match(r'^(\d{8})_', fn)
    return m.group(1) if m else '00000000'

def save_thumb(im, out_dir, out_name):
    """Square center-crop thumb for the grid; returns the file's public path suffix."""
    tdir = os.path.join(out_dir, 'thumbs'); os.makedirs(tdir, exist_ok=True)
    w, h = im.size; side = min(w, h)
    t = im.crop(((w - side) // 2, (h - side) // 2, (w + side) // 2, (h + side) // 2))
    if side > THUMB: t = t.resize((THUMB, THUMB), Image.LANCZOS)
    t.save(os.path.join(tdir, out_name), 'WEBP', quality=TQ, method=6)

def process(collection_dir, out_dir, key):
    """Read <collection_dir>/Portfolio, write webp to out_dir, return photo dicts."""
    srcdir = os.path.join(collection_dir, SRC_SUB)
    if not os.path.isdir(srcdir): return []
    files = sorted(f for f in os.listdir(srcdir) if not f.startswith('.') and title_from(f))
    if not files: return []
    os.makedirs(out_dir, exist_ok=True)
    # remove only prior files whose photo IS in the folder now (keep cover.webp
    # and any repo-only photos not yet in the folders).
    gen_slugs = {slugify(title_from(f)) for f in files}
    for f in os.listdir(out_dir):
        m = re.match(r'^\d+-(.+)\.webp$', f)
        if m and m.group(1) in gen_slugs: os.remove(os.path.join(out_dir, f))
    photos = []
    for i, fn in enumerate(sorted(files, key=date_from), 1):   # filenames numbered by date asc
        title, date = title_from(fn), date_from(fn)
        nn = f'{i:02d}'; out_name = f'{nn}-{slugify(title)}.webp'
        im = Image.open(os.path.join(srcdir, fn)).convert('RGB')
        w, h = im.size; scale = min(1.0, MAXEDGE / max(w, h))
        if scale < 1.0: im = im.resize((round(w*scale), round(h*scale)), Image.LANCZOS)
        rel = os.path.relpath(out_dir, PUB).replace(os.sep, '/')
        im.save(os.path.join(out_dir, out_name), 'WEBP', quality=Q, method=6)
        save_thumb(im, out_dir, out_name)
        photos.append({'id': f'{key}-{nn}', 'title': title,
                       'src': f'/photography/{rel}/{out_name}',
                       'thumb': f'/photography/{rel}/thumbs/{out_name}',
                       'width': im.size[0], 'height': im.size[1], 'date': date})
    # cover.webp: create from newest photo only if missing (don't clobber curated covers)
    cover = os.path.join(out_dir, 'cover.webp')
    if not os.path.exists(cover) and photos:
        newest = max(photos, key=lambda p: p['date'])
        shutil.copy(os.path.join(out_dir, os.path.basename(newest['src'])), cover)
    return photos

GEN = {}

# ── Works ──
works_dir = os.path.join(MASTER, 'Works')
for name in sorted(os.listdir(works_dir)) if os.path.isdir(works_dir) else []:
    d = os.path.join(works_dir, name)
    if not os.path.isdir(d): continue
    slug = slugify(name)
    photos = process(d, os.path.join(PUB, slug), slug)
    if photos: GEN[slug] = photos; print(f'work  {slug}: {len(photos)}')

# ── Studies ──
studies_dir = os.path.join(MASTER, 'Studies')
for name in sorted(os.listdir(studies_dir)) if os.path.isdir(studies_dir) else []:
    d = os.path.join(studies_dir, name)
    if not os.path.isdir(d): continue
    slug = slugify(name)
    photos = process(d, os.path.join(PUB, 'studies', slug), f'study-{slug}')
    if photos: GEN[slug] = photos; print(f'study {slug}: {len(photos)}')

# ── emit data/generated.ts ──
lines = [
  '// AUTO-GENERATED by scripts/sync-photos.py — do not edit by hand.',
  '// Photo lists pulled from <master>/{Works,Studies}/<name>/Portfolio/. Re-run to update.',
  '',
  'export interface GenPhoto { id: string; title: string; src: string; thumb?: string; width: number; height: number; date: string; }',
  '',
  'export const GEN: Record<string, GenPhoto[]> = {',
]
for slug in sorted(GEN):
    lines.append(f'  {slug!r}: [')
    for p in GEN[slug]:
        lines.append('    { id: %r, title: %r, src: %r, thumb: %r, width: %d, height: %d, date: %r },'
                     % (p['id'], p['title'], p['src'], p['thumb'], p['width'], p['height'], p['date']))
    lines.append('  ],')
lines.append('};')
open(os.path.join(REPO, 'data', 'generated.ts'), 'w').write('\n'.join(lines) + '\n')
print('collections:', len(GEN), '| photos:', sum(len(v) for v in GEN.values()))
