#!/usr/bin/env python3
"""Sync Loose -> repo public webp + data/loose.ts.
Source of truth: <master>/Loose/<RANGE>/Portfolio/*.jpg  (frameless, native aspect).
The Web/ copies are SQUARE + FRAMED for social media — do NOT use them here.
Run from repo root."""
import os, re, shutil
from PIL import Image

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MASTER = os.path.abspath(os.path.join(REPO, '..', '..'))
LOOSE = os.path.join(MASTER, 'Loose')
OUT = os.path.join(REPO, 'public', 'photography', 'loose')
MAXEDGE, Q = 1600, 80   # web-optimized: smaller = faster galleries
SRC_SUB = 'Portfolio'   # frameless copies (NOT Web = framed social)
# Hand-picked cover per range (by photo slug). Falls back to first photo.
COVERS = {'2012-2016': 'sunburst', '2017-2021': 'dominion', '2022-2026': 'lookout'}

def slugify(s): return re.sub(r'(^-|-$)', '', re.sub(r'[^a-z0-9]+', '-', s.lower()))
def title_from(fn):
    m = re.match(r'^\d{8}_(.+)_' + SRC_SUB.lower() + r'\.(jpe?g|png|webp)$', fn, re.I)
    return m.group(1).replace('_', ' ') if m else None

# wipe previous output so stale year folders don't linger
if os.path.isdir(OUT): shutil.rmtree(OUT)
os.makedirs(OUT, exist_ok=True)

ranges = sorted([d for d in os.listdir(LOOSE) if re.fullmatch(r'\d{4}-\d{4}', d)], reverse=True)
data = []
for r in ranges:
    srcdir = os.path.join(LOOSE, r, SRC_SUB)
    if not os.path.isdir(srcdir): continue
    # newest -> oldest by capture date (YYYYMMDD filename prefix)
    files = sorted((f for f in os.listdir(srcdir) if not f.startswith('.') and title_from(f)), reverse=True)
    rdir = os.path.join(OUT, r); os.makedirs(rdir, exist_ok=True)
    photos = []
    for i, fn in enumerate(files, 1):
        title = title_from(fn); nn = f'{i:02d}'
        out_name = f'{nn}-{slugify(title)}.webp'
        im = Image.open(os.path.join(srcdir, fn)).convert('RGB')
        w, h = im.size; scale = min(1.0, MAXEDGE / max(w, h))
        if scale < 1.0: im = im.resize((round(w*scale), round(h*scale)), Image.LANCZOS)
        im.save(os.path.join(rdir, out_name), 'WEBP', quality=Q, method=6)
        photos.append((f'loose-{r}-{nn}', title, f'/photography/loose/{r}/{out_name}'))
    if photos:
        data.append((r, photos)); print(f'{r}: {len(photos)} photos (frameless)')

lines = [
  '// AUTO-GENERATED by scripts/sync-loose.py — do not edit by hand.',
  '// Source: <master>/Loose/<range>/Portfolio/ (frameless). Re-run to update.',
  '',
  'export interface LoosePhoto { id: string; title: string; src: string; }',
  'export interface LooseGroup { year: string; coverPhoto: string; photos: LoosePhoto[]; }',
  '',
  'export const looseYears: LooseGroup[] = [',
]
for r, photos in data:
    cslug = COVERS.get(r)
    cover = next((src for _, _, src in photos if src.endswith(f'-{cslug}.webp')), photos[0][2])
    lines.append(f'  {{ year: {r!r}, coverPhoto: {cover!r}, photos: [')
    for pid, title, src in photos:
        lines.append(f'    {{ id: {pid!r}, title: {title!r}, src: {src!r} }},')
    lines.append('  ] },')
lines.append('];')
open(os.path.join(REPO, 'data', 'loose.ts'), 'w').write('\n'.join(lines) + '\n')
print('groups:', len(data), '| photos:', sum(len(p) for _, p in data))
