#!/usr/bin/env python3
"""Sync Loose web-version copies -> repo public webp + data/loose.ts.
Source of truth: <master>/Loose/<YYYY>/Web/*.jpg (aligned with the archive).
Run from repo root. Master folder is two levels up (_webpage/site -> master)."""
import os, re, sys
from PIL import Image

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MASTER = os.path.abspath(os.path.join(REPO, '..', '..'))
LOOSE = os.path.join(MASTER, 'Loose')
OUT = os.path.join(REPO, 'public', 'photography', 'loose')
MAXEDGE, Q = 2000, 82

def slugify(s): return re.sub(r'(^-|-$)', '', re.sub(r'[^a-z0-9]+', '-', s.lower()))
def title_from(fn):
    m = re.match(r'^\d{8}_(.+)_web\.(jpe?g|png|webp)$', fn, re.I)
    return m.group(1).replace('_', ' ') if m else None

years = sorted([d for d in os.listdir(LOOSE) if re.fullmatch(r'\d{4}', d)], reverse=True)
data = []
for y in years:
    webdir = os.path.join(LOOSE, y, 'Web')
    if not os.path.isdir(webdir): continue
    files = sorted(f for f in os.listdir(webdir) if not f.startswith('.') and title_from(f))
    ydir = os.path.join(OUT, y); os.makedirs(ydir, exist_ok=True)
    photos = []
    for i, fn in enumerate(files, 1):
        title = title_from(fn); nn = f'{i:02d}'; slug = slugify(title)
        out_name = f'{nn}-{slug}.webp'
        im = Image.open(os.path.join(webdir, fn)).convert('RGB')
        w, h = im.size; scale = min(1.0, MAXEDGE / max(w, h))
        if scale < 1.0: im = im.resize((round(w*scale), round(h*scale)), Image.LANCZOS)
        im.save(os.path.join(ydir, out_name), 'WEBP', quality=Q, method=6)
        photos.append((f'loose-{y}-{nn}', title, f'/photography/loose/{y}/{out_name}'))
    if photos:
        data.append((y, photos))
        print(f'{y}: {len(photos)} photos')

# emit data/loose.ts
lines = [
  '// AUTO-GENERATED by scripts/sync-loose.py — do not edit by hand.',
  '// Source of truth: <master>/Loose/<year>/Web/. Re-run the script to update.',
  '',
  'export interface LoosePhoto { id: string; title: string; src: string; }',
  'export interface LooseYear { year: string; coverPhoto: string; photos: LoosePhoto[]; }',
  '',
  'export const looseYears: LooseYear[] = [',
]
for y, photos in data:
    lines.append(f'  {{ year: {y!r}, coverPhoto: {photos[0][2]!r}, photos: [')
    for pid, title, src in photos:
        lines.append(f'    {{ id: {pid!r}, title: {title!r}, src: {src!r} }},')
    lines.append('  ] },')
lines.append('];')
with open(os.path.join(REPO, 'data', 'loose.ts'), 'w') as f:
    f.write('\n'.join(lines) + '\n')
print('total years:', len(data), '| photos:', sum(len(p) for _, p in data))
